### PR TITLE
Add new sensor icons

### LINKED ISSUE #379: Add icons for new sensors
Add icons for new sensors on front-end for SCK 2.1 and other prev versions:

Screen Shot 2019-04-25 at 13 11 08

**Icons in SVG:**[sck-21-icons.zip](https://github.com/fablabbcn/smartcitizen-web/files/3116651/sck-21-icons.zip)

**Naming**

Screen Shot 2019-04-25 at 13 25 20

**Implementation**

https://github.com/fablabbcn/smartcitizen-web/blob/04f2b18a0073048cda8ce00a908316e3b628e3b3/src/app/core/utils/sensorUtils.service.js#L136-L171

### PR DESCRIPTION
**Pull request by tuengominh**
I added new sensor icons. Closes #379 @viktorsmari

### CODE REVIEW

**Comment by viktorsmari** [comment]
@tuengominh are the icons smaller than before?
If you look at https://smartcitizen.me/kits/5353 

Before:

After:

**Comment by tuengominh** [comment]
@viktorsmari Ah because the new .svg files are actually smaller. I will find exactly where can I change the size of the icon and fix it.

**Comment by tuengominh** [comment]
Fixed :) @viktorsmari Please help me to check again
Screen Shot 2019-05-14 at 7 43 27 PM

**Comment by viktorsmari** [comment]
Did you do `git add .` because you are also committing the package* files?

**Pull request merged**
